//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 05:22:23 PM CST 
//

package org.tylor.hkp.client.bizModel.classData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 课堂数据统计配置获取 响应的 Java 类。
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pack">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PPVSPMessage">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Params">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ConfigXML">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ClassDataControl">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                                         &lt;/sequence>
 *                                                         &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "pack" })
@XmlRootElement(name = "Message")
public class RhcdGetConfigResponseMessage {

	@XmlElement(name = "Pack", required = true)
	protected RhcdGetConfigResponseMessage.Pack pack;

	/**
	 * Gets the value of the pack property.
	 *
	 * @return possible object is {@link RhcdGetConfigResponseMessage.Pack }
	 *
	 */
	public RhcdGetConfigResponseMessage.Pack getPack() {
		return pack;
	}

	/**
	 * Sets the value of the pack property.
	 *
	 * @param value
	 *            allowed object is {@link RhcdGetConfigResponseMessage.Pack }
	 *
	 */
	public void setPack(RhcdGetConfigResponseMessage.Pack value) {
		this.pack = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="PPVSPMessage">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Params">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="ConfigXML">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="ClassDataControl">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
	 *                                               &lt;/sequence>
	 *                                               &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "ppvspMessage" })
	public static class Pack {

		@XmlElement(name = "PPVSPMessage", required = true)
		protected RhcdGetConfigResponseMessage.Pack.PPVSPMessage ppvspMessage;
		@XmlAttribute(name = "type")
		protected String type;

		/**
		 * Gets the value of the ppvspMessage property.
		 *
		 * @return possible object is
		 *         {@link RhcdGetConfigResponseMessage.Pack.PPVSPMessage }
		 *
		 */
		public RhcdGetConfigResponseMessage.Pack.PPVSPMessage getPPVSPMessage() {
			return ppvspMessage;
		}

		/**
		 * Sets the value of the ppvspMessage property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link RhcdGetConfigResponseMessage.Pack.PPVSPMessage }
		 *
		 */
		public void setPPVSPMessage(RhcdGetConfigResponseMessage.Pack.PPVSPMessage value) {
			this.ppvspMessage = value;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setType(String value) {
			this.type = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Params">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="ConfigXML">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="ClassDataControl">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
		 *                                     &lt;/sequence>
		 *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "version", "sequence", "commandType", "whichCommand", "status", "description", "params" })
		public static class PPVSPMessage {

			@XmlElement(name = "Version", required = true)
			protected String version;
			@XmlElement(name = "Sequence")
			protected int sequence;
			@XmlElement(name = "CommandType", required = true)
			protected String commandType;
			@XmlElement(name = "WhichCommand", required = true)
			protected String whichCommand;
			@XmlElement(name = "Status")
			protected int status;
			@XmlElement(name = "Description", required = true)
			protected String description;
			@XmlElement(name = "Params", required = true)
			protected RhcdGetConfigResponseMessage.Pack.PPVSPMessage.Params params;

			/**
			 * Gets the value of the version property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getVersion() {
				return version;
			}

			/**
			 * Sets the value of the version property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setVersion(String value) {
				this.version = value;
			}

			/**
			 * Gets the value of the sequence property.
			 *
			 */
			public int getSequence() {
				return sequence;
			}

			/**
			 * Sets the value of the sequence property.
			 *
			 */
			public void setSequence(int value) {
				this.sequence = value;
			}

			/**
			 * Gets the value of the commandType property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getCommandType() {
				return commandType;
			}

			/**
			 * Sets the value of the commandType property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setCommandType(String value) {
				this.commandType = value;
			}

			/**
			 * Gets the value of the whichCommand property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getWhichCommand() {
				return whichCommand;
			}

			/**
			 * Sets the value of the whichCommand property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setWhichCommand(String value) {
				this.whichCommand = value;
			}

			/**
			 * Gets the value of the status property.
			 *
			 */
			public int getStatus() {
				return status;
			}

			/**
			 * Sets the value of the status property.
			 *
			 */
			public void setStatus(int value) {
				this.status = value;
			}

			/**
			 * Gets the value of the description property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the params property.
			 *
			 * @return possible object is
			 *         {@link RhcdGetConfigResponseMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public RhcdGetConfigResponseMessage.Pack.PPVSPMessage.Params getParams() {
				return params;
			}

			/**
			 * Sets the value of the params property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RhcdGetConfigResponseMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public void setParams(RhcdGetConfigResponseMessage.Pack.PPVSPMessage.Params value) {
				this.params = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="ConfigXML">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="ClassDataControl">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
			 *                           &lt;/sequence>
			 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}int" />
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "configXML" })
			public static class Params {

				@XmlElement(name = "ConfigXML", required = true)
				protected String configXML;
				@XmlElement(name = "Status", required = true)
				protected String status;

				/**
				 * 获取configXML属性的值。
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getConfigXML() {
					return configXML;
				}

				/**
				 * 设置configXML属性的值。
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setConfigXML(String value) {
					this.configXML = value;
				}

				/**
				 * 获取status属性的值。
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getStatus() {
					return status;
				}

				/**
				 * 设置status属性的值。
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setStatus(String value) {
					this.status = value;
				}

			}

		}

	}

}
