//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 07:19:31 PM CST 
//

package org.tylor.hkp.client.bizModel.classData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 课堂大数据列表获取 请求: CMS->VAG
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DevId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DevIndexCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pack">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PPVSPMessage">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Command" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Params">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ConfigCmd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ConfigParam1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ConfigXML">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "devId", "devIndexCode", "pack" })
@XmlRootElement(name = "Message")
public class RhcdDataRequestMessage {

	@XmlElement(name = "DevId")
	protected long devId;
	@XmlElement(name = "DevIndexCode", required = true)
	protected String devIndexCode;
	@XmlElement(name = "Pack", required = true)
	protected RhcdDataRequestMessage.Pack pack = new Pack();

	/**
	 * Gets the value of the devId property.
	 *
	 */
	public long getDevId() {
		return devId;
	}

	/**
	 * Sets the value of the devId property.
	 *
	 */
	public void setDevId(long value) {
		this.devId = value;
	}

	/**
	 * Gets the value of the devIndexCode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDevIndexCode() {
		return devIndexCode;
	}

	/**
	 * Sets the value of the devIndexCode property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDevIndexCode(String value) {
		this.devIndexCode = value;
	}

	/**
	 * Gets the value of the pack property.
	 *
	 * @return possible object is {@link RhcdDataRequestMessage.Pack }
	 *
	 */
	public RhcdDataRequestMessage.Pack getPack() {
		return pack;
	}

	/**
	 * Sets the value of the pack property.
	 *
	 * @param value
	 *            allowed object is {@link RhcdDataRequestMessage.Pack }
	 *
	 */
	public void setPack(RhcdDataRequestMessage.Pack value) {
		this.pack = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="PPVSPMessage">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Command" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Params">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="ConfigCmd" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ConfigParam1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                             &lt;element name="ConfigXML">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                       &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "ppvspMessage" })
	public static class Pack {

		@XmlElement(name = "PPVSPMessage", required = true)
		protected RhcdDataRequestMessage.Pack.PPVSPMessage ppvspMessage = new PPVSPMessage();
		@XmlAttribute(name = "type")
		protected String type = "PPVSP";

		/**
		 * Gets the value of the ppvspMessage property.
		 *
		 * @return possible object is
		 *         {@link RhcdDataRequestMessage.Pack.PPVSPMessage }
		 *
		 */
		public RhcdDataRequestMessage.Pack.PPVSPMessage getPPVSPMessage() {
			return ppvspMessage;
		}

		/**
		 * Sets the value of the ppvspMessage property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link RhcdDataRequestMessage.Pack.PPVSPMessage }
		 *
		 */
		public void setPPVSPMessage(RhcdDataRequestMessage.Pack.PPVSPMessage value) {
			this.ppvspMessage = value;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setType(String value) {
			this.type = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Command" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Params">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="ConfigCmd" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ConfigParam1" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                   &lt;element name="ConfigXML">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                             &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "version", "sequence", "commandType", "command", "params" })
		public static class PPVSPMessage {

			@XmlElement(name = "Version", required = true)
			protected String version = "2.0";
			@XmlElement(name = "Sequence")
			protected int sequence;
			@XmlElement(name = "CommandType", required = true)
			protected String commandType = "REQUEST";
			@XmlElement(name = "Command", required = true)
			protected String command = "TRANSPARENTCONFIG";
			@XmlElement(name = "Params", required = true)
			protected RhcdDataRequestMessage.Pack.PPVSPMessage.Params params = new Params();

			/**
			 * Gets the value of the version property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getVersion() {
				return version;
			}

			/**
			 * Sets the value of the version property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setVersion(String value) {
				this.version = value;
			}

			/**
			 * Gets the value of the sequence property.
			 *
			 */
			public int getSequence() {
				return sequence;
			}

			/**
			 * Sets the value of the sequence property.
			 *
			 */
			public void setSequence(int value) {
				this.sequence = value;
			}

			/**
			 * Gets the value of the commandType property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getCommandType() {
				return commandType;
			}

			/**
			 * Sets the value of the commandType property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setCommandType(String value) {
				this.commandType = value;
			}

			/**
			 * Gets the value of the command property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getCommand() {
				return command;
			}

			/**
			 * Sets the value of the command property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setCommand(String value) {
				this.command = value;
			}

			/**
			 * Gets the value of the params property.
			 *
			 * @return possible object is
			 *         {@link RhcdDataRequestMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public RhcdDataRequestMessage.Pack.PPVSPMessage.Params getParams() {
				return params;
			}

			/**
			 * Sets the value of the params property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RhcdDataRequestMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public void setParams(RhcdDataRequestMessage.Pack.PPVSPMessage.Params value) {
				this.params = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 *
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="ConfigCmd" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ConfigParam1" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *         &lt;element name="ConfigXML">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                   &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "configCmd", "configParam1", "configXML" })
			public static class Params {

				@XmlElement(name = "ConfigCmd", required = true)
				protected String configCmd = "TransparentConfig";
				@XmlElement(name = "ConfigParam1", required = true)
				protected String configParam1 = "GetStatisticDdataList";
				@XmlElement(name = "ConfigXML", required = true)
				protected RhcdDataRequestMessage.Pack.PPVSPMessage.Params.ConfigXML configXML = new ConfigXML();

				/**
				 * Gets the value of the configCmd property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getConfigCmd() {
					return configCmd;
				}

				/**
				 * Sets the value of the configCmd property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setConfigCmd(String value) {
					this.configCmd = value;
				}

				/**
				 * Gets the value of the configParam1 property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getConfigParam1() {
					return configParam1;
				}

				/**
				 * Sets the value of the configParam1 property.
				 *
				 * @param value
				 *            allowed object is {@link String }
				 *
				 */
				public void setConfigParam1(String value) {
					this.configParam1 = value;
				}

				/**
				 * Gets the value of the configXML property.
				 *
				 * @return possible object is
				 *         {@link RhcdDataRequestMessage.Pack.PPVSPMessage.Params.ConfigXML }
				 *
				 */
				public RhcdDataRequestMessage.Pack.PPVSPMessage.Params.ConfigXML getConfigXML() {
					return configXML;
				}

				/**
				 * Sets the value of the configXML property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link RhcdDataRequestMessage.Pack.PPVSPMessage.Params.ConfigXML }
				 *
				 */
				public void setConfigXML(RhcdDataRequestMessage.Pack.PPVSPMessage.Params.ConfigXML value) {
					this.configXML = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "typeTarget", "startTime", "stopTime" })
				public static class ConfigXML {

					@XmlElement(name = "TypeTarget")
					protected int typeTarget;
					@XmlElement(name = "StartTime", required = true)
					protected String startTime;
					@XmlElement(name = "StopTime", required = true)
					protected String stopTime;

					/**
					 * Gets the value of the typeTarget property.
					 * 
					 */
					public int getTypeTarget() {
						return typeTarget;
					}

					/**
					 * Sets the value of the typeTarget property.
					 * 
					 */
					public void setTypeTarget(int value) {
						this.typeTarget = value;
					}

					/**
					 * Gets the value of the startTime property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getStartTime() {
						return startTime;
					}

					/**
					 * Sets the value of the startTime property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setStartTime(String value) {
						this.startTime = value;
					}

					/**
					 * Gets the value of the stopTime property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getStopTime() {
						return stopTime;
					}

					/**
					 * Sets the value of the stopTime property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setStopTime(String value) {
						this.stopTime = value;
					}

				}

			}

		}

	}

}
