//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.06 at 07:27:29 PM CST 
//

package org.tylor.hkp.client.bizModel.classData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 课堂大数据列表获取 响应:VAG->CMS
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pack">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PPVSPMessage">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Params">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ConfigXML">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Item" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                           &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "pack" })
@XmlRootElement(name = "Message")
public class RhcdDataResponseMessage {

	@XmlElement(name = "Pack", required = true)
	protected RhcdDataResponseMessage.Pack pack;

	/**
	 * Gets the value of the pack property.
	 *
	 * @return possible object is {@link RhcdDataResponseMessage.Pack }
	 *
	 */
	public RhcdDataResponseMessage.Pack getPack() {
		return pack;
	}

	/**
	 * Sets the value of the pack property.
	 *
	 * @param value
	 *            allowed object is {@link RhcdDataResponseMessage.Pack }
	 *
	 */
	public void setPack(RhcdDataResponseMessage.Pack value) {
		this.pack = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="PPVSPMessage">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="Params">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="ConfigXML">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="Item" maxOccurs="unbounded">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                                 &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                                 &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "ppvspMessage" })
	public static class Pack {

		@XmlElement(name = "PPVSPMessage", required = true)
		protected RhcdDataResponseMessage.Pack.PPVSPMessage ppvspMessage;
		@XmlAttribute(name = "type")
		protected String type;

		/**
		 * Gets the value of the ppvspMessage property.
		 *
		 * @return possible object is
		 *         {@link RhcdDataResponseMessage.Pack.PPVSPMessage }
		 *
		 */
		public RhcdDataResponseMessage.Pack.PPVSPMessage getPPVSPMessage() {
			return ppvspMessage;
		}

		/**
		 * Sets the value of the ppvspMessage property.
		 *
		 * @param value
		 *            allowed object is
		 *            {@link RhcdDataResponseMessage.Pack.PPVSPMessage }
		 *
		 */
		public void setPPVSPMessage(RhcdDataResponseMessage.Pack.PPVSPMessage value) {
			this.ppvspMessage = value;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value
		 *            allowed object is {@link String }
		 *
		 */
		public void setType(String value) {
			this.type = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="CommandType" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="WhichCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="Params">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="ConfigXML">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="Item" maxOccurs="unbounded">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                                       &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                       &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "version", "sequence", "commandType", "whichCommand", "status", "description", "params" })
		public static class PPVSPMessage {

			@XmlElement(name = "Version", required = true)
			protected String version;
			@XmlElement(name = "Sequence")
			protected int sequence;
			@XmlElement(name = "CommandType", required = true)
			protected String commandType;
			@XmlElement(name = "WhichCommand", required = true)
			protected String whichCommand;
			@XmlElement(name = "Status")
			protected int status;
			@XmlElement(name = "Description", required = true)
			protected String description;
			@XmlElement(name = "Params", required = true)
			protected RhcdDataResponseMessage.Pack.PPVSPMessage.Params params;

			/**
			 * Gets the value of the version property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getVersion() {
				return version;
			}

			/**
			 * Sets the value of the version property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setVersion(String value) {
				this.version = value;
			}

			/**
			 * Gets the value of the sequence property.
			 *
			 */
			public int getSequence() {
				return sequence;
			}

			/**
			 * Sets the value of the sequence property.
			 *
			 */
			public void setSequence(int value) {
				this.sequence = value;
			}

			/**
			 * Gets the value of the commandType property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getCommandType() {
				return commandType;
			}

			/**
			 * Sets the value of the commandType property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setCommandType(String value) {
				this.commandType = value;
			}

			/**
			 * Gets the value of the whichCommand property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getWhichCommand() {
				return whichCommand;
			}

			/**
			 * Sets the value of the whichCommand property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setWhichCommand(String value) {
				this.whichCommand = value;
			}

			/**
			 * Gets the value of the status property.
			 *
			 */
			public int getStatus() {
				return status;
			}

			/**
			 * Sets the value of the status property.
			 *
			 */
			public void setStatus(int value) {
				this.status = value;
			}

			/**
			 * Gets the value of the description property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 *
			 * @param value
			 *            allowed object is {@link String }
			 *
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the params property.
			 *
			 * @return possible object is
			 *         {@link RhcdDataResponseMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public RhcdDataResponseMessage.Pack.PPVSPMessage.Params getParams() {
				return params;
			}

			/**
			 * Sets the value of the params property.
			 *
			 * @param value
			 *            allowed object is
			 *            {@link RhcdDataResponseMessage.Pack.PPVSPMessage.Params }
			 *
			 */
			public void setParams(RhcdDataResponseMessage.Pack.PPVSPMessage.Params value) {
				this.params = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 *
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="ConfigXML">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="Item" maxOccurs="unbounded">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                             &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                             &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "configXML" })
			public static class Params {

				@XmlElement(name = "ConfigXML", required = true)
				protected RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML configXML;

				/**
				 * Gets the value of the configXML property.
				 *
				 * @return possible object is
				 *         {@link RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML }
				 *
				 */
				public RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML getConfigXML() {
					return configXML;
				}

				/**
				 * Sets the value of the configXML property.
				 *
				 * @param value
				 *            allowed object is
				 *            {@link RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML }
				 *
				 */
				public void setConfigXML(RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML value) {
					this.configXML = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 *
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 *
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="Item" maxOccurs="unbounded">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *                   &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                   &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 *
				 *
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "item" })
				public static class ConfigXML {

					@XmlElement(name = "Item", required = true)
					protected List<Item> item;

					/**
					 * Gets the value of the item property.
					 *
					 * <p>
					 * This accessor method returns a reference to the live
					 * list, not a snapshot. Therefore any modification you make
					 * to the returned list will be present inside the JAXB
					 * object. This is why there is not a <CODE>set</CODE>
					 * method for the item property.
					 *
					 * <p>
					 * For example, to add a new item, do as follows:
					 *
					 * <pre>
					 * getItem().add(newItem);
					 * </pre>
					 *
					 *
					 * <p>
					 * Objects of the following type(s) are allowed in the list
					 * {@link RhcdDataResponseMessage.Pack.PPVSPMessage.Params.ConfigXML.Item }
					 *
					 *
					 */
					public List<Item> getItem() {
						if (item == null) {
							item = new ArrayList<Item>();
						}
						return this.item;
					}

					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * 
					 * <p>
					 * The following schema fragment specifies the expected
					 * content contained within this class.
					 * 
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="TypeTarget" type="{http://www.w3.org/2001/XMLSchema}int"/>
					 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *         &lt;element name="StopTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "typeTarget", "startTime", "stopTime" })
					public static class Item {

						@XmlElement(name = "TypeTarget")
						protected int typeTarget;
						@XmlElement(name = "StartTime", required = true)
						protected String startTime;
						@XmlElement(name = "StopTime", required = true)
						protected String stopTime;

						/**
						 * Gets the value of the typeTarget property.
						 * 
						 */
						public int getTypeTarget() {
							return typeTarget;
						}

						/**
						 * Sets the value of the typeTarget property.
						 * 
						 */
						public void setTypeTarget(int value) {
							this.typeTarget = value;
						}

						/**
						 * Gets the value of the startTime property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getStartTime() {
							return startTime;
						}

						/**
						 * Sets the value of the startTime property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setStartTime(String value) {
							this.startTime = value;
						}

						/**
						 * Gets the value of the stopTime property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getStopTime() {
							return stopTime;
						}

						/**
						 * Sets the value of the stopTime property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setStopTime(String value) {
							this.stopTime = value;
						}

					}

				}

			}

		}

	}

}
